name: 问题反馈
description: 反馈使用中遇到的问题
title: "[反馈] "
labels: ["bug"]
body:
  - type: input
    id: video_url
    attributes:
      label: YouTube 视频地址
      description: 请粘贴出问题的 YouTube 视频链接
      placeholder: https://www.youtube.com/watch?v=...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 问题描述
      description: 请描述你遇到的问题
      placeholder: 例如：字幕没有显示 / 翻译不准确 / 插件报错...
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: 插件版本确认
      description: "当前最新测试版：v1.8.12。请在 chrome://extensions/?id=dhnnaoekbmgafnpfejifanamaleffdla 查看你的版本号"
      options:
        - 确认是最新版 v1.8.12
        - 不是最新版 / 不确定
    validations:
      required: true
